### PR TITLE
404 Fixed, optimized and reorganized code

### PR DESCRIPTION
**Pull request by overjt**

### CODE REVIEW

**Comment by fojas** [comment]
This still suffers from the same issue as https://github.com/fojas/cleverbot-node/pull/12. The prepare statement makes a call asynchronously, so some requests will not have the correct cookie.

It is likely that fixing this will require changing the interface of the Cleverbot module. The `prepare` function will probably need to take a callback.

**Comment by overjt** [comment]
@fojas 

You do not need to call "prepare" every time you want to send something to cleverbot, you only need to get the cookie once and send subsequent requests with that cookie.

My patch called to "prepare" in the constructor and get the cookie when the object is created.

image

```javascript
var Cleverbot = require('../lib/cleverbot');
var CBots = [new Cleverbot,new Cleverbot]
  , i = 0
  , name = ['Bob Loblaw', 'Stan Sitwell']
  , callback = function callback(resp){
    CBots[i].write(resp['message'],callback);
    console.log(name[i = ( ( i + 1 ) %2)],' : ',  resp['message'])
  };

callback({message:'Just a small town girl'})
```

**Comment by fojas** [comment]
Yes, but in the sample that you showed, the first two responses are `<html>`. That is because the cookie is not set yet when those requests are made. There needs to be a way to make the requests wait for the initial cookie request to return.

**Comment by devlin5** [comment]
How does cleverbot.io do this?  Also, I noticed that they didn't stop working when the session change was made.

**Comment by fojas** [comment]
This has been fixed here, https://github.com/fojas/cleverbot-node/issues/11

**Pull request closed without merging**
